### ISSUE TITLE
Test suite fails for perl 5.21.5 and later (Modification of a read-only value attempted)

### ISSUE THREAD

**Issue by eserte** [ingydotnet/boolean-pm#7] opened 2015-01-01 09:59 UTC
This issue was mentioned in some comments in https://github.com/ingydotnet/boolean-pm/issues/5 but maybe is another issue, as it happens on all systems, not only linux systems. Failure happens with boolean 0.42 and 0.43.

**Comment by kentfredric** [comment] 2015-01-01 15:09
"Modification of readonly value" is the cause in #5 as well, just the way it manifests is that its in an `eval` , so the specific error gets suppressed. 

In #5, the problem is exposed by JSON::XS, but the same lines of code trigger the same bug in 5.21.5 

0.43 released in the last 6 hours made no impact on either bug because it was a documentation only change: https://metacpan.org/diff/file?target=INGY/boolean-0.43/&source=INGY/boolean-0.42/

**Closed** 2015-01-31 21:55 UTC
